/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppNotesRouteImport } from './routes/_app/notes'
import { Route as AppAppsRouteImport } from './routes/_app/apps'
import { Route as AppProfileIndexRouteImport } from './routes/_app/profile/index'
import { Route as AppNotesIndexRouteImport } from './routes/_app/notes/index'
import { Route as ApiTestResetDbRouteImport } from './routes/api/test/reset-db'
import { Route as ApiTestLoginRouteImport } from './routes/api/test/login'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as AppProfileEditRouteImport } from './routes/_app/profile/edit'
import { Route as AppNotesNewRouteImport } from './routes/_app/notes/new'
import { Route as AppProfileHistoryIndexRouteImport } from './routes/_app/profile/history/index'
import { Route as ApiAuthFeishuLoginRouteImport } from './routes/api/auth/feishu/login'
import { Route as ApiAuthFeishuJsapiRouteImport } from './routes/api/auth/feishu/jsapi'
import { Route as ApiAuthFeishuCallbackRouteImport } from './routes/api/auth/feishu/callback'
import { Route as AppProfileHistoryVersionRouteImport } from './routes/_app/profile/history/$version'
import { Route as AppNotesIdEditRouteImport } from './routes/_app/notes/$id/edit'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesRoute = AppNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AppRoute,
} as any)
const AppAppsRoute = AppAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileIndexRoute = AppProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProfileRoute,
} as any)
const AppNotesIndexRoute = AppNotesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppNotesRoute,
} as any)
const ApiTestResetDbRoute = ApiTestResetDbRouteImport.update({
  id: '/api/test/reset-db',
  path: '/api/test/reset-db',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestLoginRoute = ApiTestLoginRouteImport.update({
  id: '/api/test/login',
  path: '/api/test/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileEditRoute = AppProfileEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppProfileRoute,
} as any)
const AppNotesNewRoute = AppNotesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppNotesRoute,
} as any)
const AppProfileHistoryIndexRoute = AppProfileHistoryIndexRouteImport.update({
  id: '/history/',
  path: '/history/',
  getParentRoute: () => AppProfileRoute,
} as any)
const ApiAuthFeishuLoginRoute = ApiAuthFeishuLoginRouteImport.update({
  id: '/api/auth/feishu/login',
  path: '/api/auth/feishu/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthFeishuJsapiRoute = ApiAuthFeishuJsapiRouteImport.update({
  id: '/api/auth/feishu/jsapi',
  path: '/api/auth/feishu/jsapi',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthFeishuCallbackRoute = ApiAuthFeishuCallbackRouteImport.update({
  id: '/api/auth/feishu/callback',
  path: '/api/auth/feishu/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileHistoryVersionRoute =
  AppProfileHistoryVersionRouteImport.update({
    id: '/history/$version',
    path: '/history/$version',
    getParentRoute: () => AppProfileRoute,
  } as any)
const AppNotesIdEditRoute = AppNotesIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AppNotesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/apps': typeof AppAppsRoute
  '/notes': typeof AppNotesRouteWithChildren
  '/profile': typeof AppProfileRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/notes/new': typeof AppNotesNewRoute
  '/profile/edit': typeof AppProfileEditRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/test/login': typeof ApiTestLoginRoute
  '/api/test/reset-db': typeof ApiTestResetDbRoute
  '/notes/': typeof AppNotesIndexRoute
  '/profile/': typeof AppProfileIndexRoute
  '/notes/$id/edit': typeof AppNotesIdEditRoute
  '/profile/history/$version': typeof AppProfileHistoryVersionRoute
  '/api/auth/feishu/callback': typeof ApiAuthFeishuCallbackRoute
  '/api/auth/feishu/jsapi': typeof ApiAuthFeishuJsapiRoute
  '/api/auth/feishu/login': typeof ApiAuthFeishuLoginRoute
  '/profile/history/': typeof AppProfileHistoryIndexRoute
}
export interface FileRoutesByTo {
  '/apps': typeof AppAppsRoute
  '/settings': typeof AppSettingsRoute
  '/': typeof AppIndexRoute
  '/notes/new': typeof AppNotesNewRoute
  '/profile/edit': typeof AppProfileEditRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/test/login': typeof ApiTestLoginRoute
  '/api/test/reset-db': typeof ApiTestResetDbRoute
  '/notes': typeof AppNotesIndexRoute
  '/profile': typeof AppProfileIndexRoute
  '/notes/$id/edit': typeof AppNotesIdEditRoute
  '/profile/history/$version': typeof AppProfileHistoryVersionRoute
  '/api/auth/feishu/callback': typeof ApiAuthFeishuCallbackRoute
  '/api/auth/feishu/jsapi': typeof ApiAuthFeishuJsapiRoute
  '/api/auth/feishu/login': typeof ApiAuthFeishuLoginRoute
  '/profile/history': typeof AppProfileHistoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/apps': typeof AppAppsRoute
  '/_app/notes': typeof AppNotesRouteWithChildren
  '/_app/profile': typeof AppProfileRouteWithChildren
  '/_app/settings': typeof AppSettingsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/notes/new': typeof AppNotesNewRoute
  '/_app/profile/edit': typeof AppProfileEditRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/test/login': typeof ApiTestLoginRoute
  '/api/test/reset-db': typeof ApiTestResetDbRoute
  '/_app/notes/': typeof AppNotesIndexRoute
  '/_app/profile/': typeof AppProfileIndexRoute
  '/_app/notes/$id/edit': typeof AppNotesIdEditRoute
  '/_app/profile/history/$version': typeof AppProfileHistoryVersionRoute
  '/api/auth/feishu/callback': typeof ApiAuthFeishuCallbackRoute
  '/api/auth/feishu/jsapi': typeof ApiAuthFeishuJsapiRoute
  '/api/auth/feishu/login': typeof ApiAuthFeishuLoginRoute
  '/_app/profile/history/': typeof AppProfileHistoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apps'
    | '/notes'
    | '/profile'
    | '/settings'
    | '/notes/new'
    | '/profile/edit'
    | '/api/auth/logout'
    | '/api/test/login'
    | '/api/test/reset-db'
    | '/notes/'
    | '/profile/'
    | '/notes/$id/edit'
    | '/profile/history/$version'
    | '/api/auth/feishu/callback'
    | '/api/auth/feishu/jsapi'
    | '/api/auth/feishu/login'
    | '/profile/history/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/apps'
    | '/settings'
    | '/'
    | '/notes/new'
    | '/profile/edit'
    | '/api/auth/logout'
    | '/api/test/login'
    | '/api/test/reset-db'
    | '/notes'
    | '/profile'
    | '/notes/$id/edit'
    | '/profile/history/$version'
    | '/api/auth/feishu/callback'
    | '/api/auth/feishu/jsapi'
    | '/api/auth/feishu/login'
    | '/profile/history'
  id:
    | '__root__'
    | '/_app'
    | '/_app/apps'
    | '/_app/notes'
    | '/_app/profile'
    | '/_app/settings'
    | '/_app/'
    | '/_app/notes/new'
    | '/_app/profile/edit'
    | '/api/auth/logout'
    | '/api/test/login'
    | '/api/test/reset-db'
    | '/_app/notes/'
    | '/_app/profile/'
    | '/_app/notes/$id/edit'
    | '/_app/profile/history/$version'
    | '/api/auth/feishu/callback'
    | '/api/auth/feishu/jsapi'
    | '/api/auth/feishu/login'
    | '/_app/profile/history/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiTestLoginRoute: typeof ApiTestLoginRoute
  ApiTestResetDbRoute: typeof ApiTestResetDbRoute
  ApiAuthFeishuCallbackRoute: typeof ApiAuthFeishuCallbackRoute
  ApiAuthFeishuJsapiRoute: typeof ApiAuthFeishuJsapiRoute
  ApiAuthFeishuLoginRoute: typeof ApiAuthFeishuLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notes': {
      id: '/_app/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AppNotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/apps': {
      id: '/_app/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AppAppsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile/': {
      id: '/_app/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof AppProfileIndexRouteImport
      parentRoute: typeof AppProfileRoute
    }
    '/_app/notes/': {
      id: '/_app/notes/'
      path: '/'
      fullPath: '/notes/'
      preLoaderRoute: typeof AppNotesIndexRouteImport
      parentRoute: typeof AppNotesRoute
    }
    '/api/test/reset-db': {
      id: '/api/test/reset-db'
      path: '/api/test/reset-db'
      fullPath: '/api/test/reset-db'
      preLoaderRoute: typeof ApiTestResetDbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test/login': {
      id: '/api/test/login'
      path: '/api/test/login'
      fullPath: '/api/test/login'
      preLoaderRoute: typeof ApiTestLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/profile/edit': {
      id: '/_app/profile/edit'
      path: '/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof AppProfileEditRouteImport
      parentRoute: typeof AppProfileRoute
    }
    '/_app/notes/new': {
      id: '/_app/notes/new'
      path: '/new'
      fullPath: '/notes/new'
      preLoaderRoute: typeof AppNotesNewRouteImport
      parentRoute: typeof AppNotesRoute
    }
    '/_app/profile/history/': {
      id: '/_app/profile/history/'
      path: '/history'
      fullPath: '/profile/history/'
      preLoaderRoute: typeof AppProfileHistoryIndexRouteImport
      parentRoute: typeof AppProfileRoute
    }
    '/api/auth/feishu/login': {
      id: '/api/auth/feishu/login'
      path: '/api/auth/feishu/login'
      fullPath: '/api/auth/feishu/login'
      preLoaderRoute: typeof ApiAuthFeishuLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/feishu/jsapi': {
      id: '/api/auth/feishu/jsapi'
      path: '/api/auth/feishu/jsapi'
      fullPath: '/api/auth/feishu/jsapi'
      preLoaderRoute: typeof ApiAuthFeishuJsapiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/feishu/callback': {
      id: '/api/auth/feishu/callback'
      path: '/api/auth/feishu/callback'
      fullPath: '/api/auth/feishu/callback'
      preLoaderRoute: typeof ApiAuthFeishuCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/profile/history/$version': {
      id: '/_app/profile/history/$version'
      path: '/history/$version'
      fullPath: '/profile/history/$version'
      preLoaderRoute: typeof AppProfileHistoryVersionRouteImport
      parentRoute: typeof AppProfileRoute
    }
    '/_app/notes/$id/edit': {
      id: '/_app/notes/$id/edit'
      path: '/$id/edit'
      fullPath: '/notes/$id/edit'
      preLoaderRoute: typeof AppNotesIdEditRouteImport
      parentRoute: typeof AppNotesRoute
    }
  }
}

interface AppNotesRouteChildren {
  AppNotesNewRoute: typeof AppNotesNewRoute
  AppNotesIndexRoute: typeof AppNotesIndexRoute
  AppNotesIdEditRoute: typeof AppNotesIdEditRoute
}

const AppNotesRouteChildren: AppNotesRouteChildren = {
  AppNotesNewRoute: AppNotesNewRoute,
  AppNotesIndexRoute: AppNotesIndexRoute,
  AppNotesIdEditRoute: AppNotesIdEditRoute,
}

const AppNotesRouteWithChildren = AppNotesRoute._addFileChildren(
  AppNotesRouteChildren,
)

interface AppProfileRouteChildren {
  AppProfileEditRoute: typeof AppProfileEditRoute
  AppProfileIndexRoute: typeof AppProfileIndexRoute
  AppProfileHistoryVersionRoute: typeof AppProfileHistoryVersionRoute
  AppProfileHistoryIndexRoute: typeof AppProfileHistoryIndexRoute
}

const AppProfileRouteChildren: AppProfileRouteChildren = {
  AppProfileEditRoute: AppProfileEditRoute,
  AppProfileIndexRoute: AppProfileIndexRoute,
  AppProfileHistoryVersionRoute: AppProfileHistoryVersionRoute,
  AppProfileHistoryIndexRoute: AppProfileHistoryIndexRoute,
}

const AppProfileRouteWithChildren = AppProfileRoute._addFileChildren(
  AppProfileRouteChildren,
)

interface AppRouteChildren {
  AppAppsRoute: typeof AppAppsRoute
  AppNotesRoute: typeof AppNotesRouteWithChildren
  AppProfileRoute: typeof AppProfileRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAppsRoute: AppAppsRoute,
  AppNotesRoute: AppNotesRouteWithChildren,
  AppProfileRoute: AppProfileRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiTestLoginRoute: ApiTestLoginRoute,
  ApiTestResetDbRoute: ApiTestResetDbRoute,
  ApiAuthFeishuCallbackRoute: ApiAuthFeishuCallbackRoute,
  ApiAuthFeishuJsapiRoute: ApiAuthFeishuJsapiRoute,
  ApiAuthFeishuLoginRoute: ApiAuthFeishuLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
